name: pdf_translator_app_test
description: "PDF Translation App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # Implement plugin untuk save data sederhana (key-value)
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.3.5

  # Untuk date time formatter
  # https://pub.dev/packages/intl
  intl: ">=0.17.0 <=0.20.1"

  # Untuk http connection
  # https://pub.dev/packages/http
  http: ^1.2.2

  # Untuk loading
  # https://pub.dev/packages/progress_dialog_null_safe
  progress_dialog_null_safe: ^3.0.0

  # Translator dari Google Translate API
  # https://pub.dev/packages/translator
  # translator: ^1.0.3+1
  
  # PDF Reader
  # https://pub.dev/packages/pdf
  # pdf: ^3.11.1

  # Untuk icon format svg
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.17

  # Untuk deteksi text
  # https://pub.dev/packages/google_mlkit_text_recognition
  google_mlkit_text_recognition: ^0.14.0

  # 
  # https://pub.dev/packages/google_mlkit_commons
  google_mlkit_commons: any

  # 
  # https://pub.dev/packages/google_mlkit_translation
  google_mlkit_translation: ^0.12.0

  # Implementasi multi language
  # https://pub.dev/packages/easy_localization/install
  easy_localization: ^3.0.7

  # Implementasi BLoC
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^9.0.0

  # 
  # https://pub.dev/packages/equatable
  equatable: ^2.0.5

  # 
  # https://pub.dev/packages/camera
  camera: ^0.11.1

  # 
  # https://pub.dev/packages/image_picker
  image_picker: ^1.1.2

  # 
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.5

  # Speech to text
  # https://pub.dev/packages/speech_to_text
  speech_to_text: ^7.0.0

  # Bentuk bubble seperti chat bubble
  # https://pub.dev/packages/bubble
  bubble: ^1.2.1

  # Check permission
  # https://pub.dev/packages/permission_handler
  permission_handler: ^11.3.1

dependency_overrides:
  google_mlkit_commons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # Untuk mendaftarkan berbagai asset image yang akan digunakan
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/action-based/
    - assets/icons/formatting/
    - assets/icons/object-based/
    - assets/icons/carbon-design-system/
    - assets/icons/carbon-design-system/16/
    - assets/icons/carbon-design-system/20/
    - assets/icons/carbon-design-system/24/
    - assets/icons/carbon-design-system/32/
    - assets/translations/
    - lib/translations/
  #- assets/certificates

  # Untuk mendaftarkan custom font yang akan digunakan
  # fonts:
  #   - family: BiomeRegular
  #     fonts:
  #       - asset: assets/fonts/biome_regular.ttf
